#!/bin/bash
# 2013 Angelo Olivera <aolivera@gmail.com>
# Helper script to set up controller nodes as NAT routers and modify routing
# table on clients

# usage: ./network client $myhostname $serverhostname
#        ./network server $myhostname

# Color escape codes
RESTORE='\033[0m'
RED='\033[00;31m'
GREEN='\033[00;32m'
YELLOW='\033[00;33m'

msg() {
    case "$1" in
        error)  echo -ne "$RED"                 >&2
                echo "$0@$hostname: ${@:2}"     >&2
                ;;
        warn)   echo -ne "$YELLOW"              >&2
                echo "$0@$hostname: ${@:2}"     >&2
                ;;
        *)      echo -ne "$GREEN"
                echo "$0@$hostname: ${@}"
    esac

    # restore normal colors
    echo -ne "$RESTORE"
    echo -ne "$RESTORE"    >&2
}

usage() {
    # print to stderr
    exec 5>&1
    exec 1>&2
    echo "Usage:"
    echo "$0 --hostname HOSTNAME --ip PRIVATE_IP server"
    echo "$0 --hostname HOSTNAME --ip PRIVATE_IP client"
    # restore stdout
    exec 0>&5
}
ARGS=$(getopt -l "client,server,hostname:,ip:,server_hostname:,server_ip:" -n "$0" -- ignore "$@")
eval set -- "$ARGS"
while true; do
    case "$1" in
        --client)
            command=client
            shift;;
        --server)
            command=server
            shift;;
        --hostname)
            hostname=$2
            shift 2;;
        --ip)
            ip=$2
            shift 2;;
        --server_hostname)
            server_hostname=$2
            shift 2;;
        --server_ip)
            server_ip=$2
            shift 2;;
        --)
            shift
            break;;
        *)
            msg error "invalid command-line option: $1"
            break;;
    esac
done

sethostname() {
    [[ $(hostname) == $hostname ]] && return 0
    msg "Setting hostname: $hostname"
    hostname $hostname
    echo $(hostname) > /etc/hostname
    if ! grep -q 127.0.0.1 /etc/hosts; then
        echo "127.0.0.1 localhost" >> /etc/hosts
    fi

    grep -q $hostname /etc/hosts && return 0
    if [[ -n $ip ]]; then
        echo "$ip $hostname" >> /etc/hosts
    else
        sed -ie "s/127.0.0.1.*/& $hostname/" /etc/hosts
    fi
}

setup_masquerade() {
    if ! /sbin/iptables -t nat -C POSTROUTING -o eth0 -j MASQUERADE 2>/dev/null; then
        msg "Configuring as NAT router"
        echo 1 > /proc/sys/net/ipv4/ip_forward
        /sbin/iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
        /sbin/iptables -A FORWARD -i eth0 -o etho -m state --state RELATED,ESTABLISHED -j ACCEPT
        /sbin/iptables -A FORWARD -i eth0 -o eth0 -j ACCEPT
    fi
}

set_default_route() {
    if ! ip ro g 1.1.1.1 | grep -q $1; then
        msg "Setting default route"
        sudo ip ro d default
        sudo ip ro a default via $1
    fi
}

if [[ -n $hostname ]]; then
    sethostname
fi

case "$command" in
    client) set_default_route $server_ip;;
    server) setup_masquerade;;
    *) msg error "Unknown action: $@"
        shift;;
esac

while [[ -n $1 ]] && [[ -n $2 ]]; do
    if ! grep -q $1 /etc/hosts; then
        echo "Adding $2 ($1) to /etc/hosts"
        echo $1 $2 >> /etc/hosts
    fi
    shift 2
done

