#!/bin/bash
# 2013 Angelo Olivera <aolivera@gmail.com>
#
# Set up remote nodes using puppet-openstack-configure
#

# kill children if script was interrupted
trap 'kill ${pids[@]} 2>/dev/null' SIGTERM
trap 'kill ${pids[@]} 2>/dev/null' SIGINT

# Color escape codes
RESTORE='\033[0m'
RED='\033[00;31m'
GREEN='\033[00;32m'
YELLOW='\033[00;33m'

msg() {
    case "$1" in
        error)  echo -ne "$RED"     >&2
                echo "$0@$hostname: ${@:2}"    >&2
                exit 1
                ;;
        warn)   echo -ne "$YELLOW"  >&2
                echo "$0@$hostname: ${@:2}"    >&2
                ;;
        *)      echo -ne "$GREEN"
                echo "$0@$hostname: ${@}"
    esac

    # restore normal colors
    echo -ne "$restore"
    echo -ne "$restore" >&2
}

usage() {
    # print to stderr
    exec 5>&1
    exec 1>&2
    echo "Usage: (-h for more information)"
    echo "$0 [[-f DESCFILE] | [-n -i IP -h HOSTNAME -c CONTROLLER_IP -n CONTROLLER_HOSTNAME -k SSH_KEY]] TESTBED"
    # restore stdout
    exec 0>&5
}

help() {
    # print to stderr
    exec 5>&1
    exec 1>&2
    echo "Usage: $0 [options] TESTBED"
    echo ""
    echo "TESTBED is the name of the set of machines where OpenStack will be installed."
    echo ""
    echo "Options:"
    echo "-f DESCFILE, --file DESCFILE"
    echo "                      Description of the tesbed with entries in key=value format"
    echo "                      default: TESTBED/TESTBED.desc"
    echo "-n, --node"
    echo "                      Configure from command-line instead of using a description file"
    echo "-k KEY, --key KEY"
    echo "                      Name of SSH key to use"
    echo "                      default: openstack"
    echo "-i IP, --ip IP"
    echo "                      Node IP address"
    echo "-h HOSTNAME, --hostname HOSTNAME"
    echo "                      Node hostname"
    echo "-c IP, --controller_ip IP"
    echo "                      Controller IP address"
    echo "-t HOSTNAME, --controller_hostname HOSTNAME"
    echo "                      Controller hostname"
    echo "-v, --verbose"
    echo "                      Show verbose progress"
    echo ""
    echo "Example:"
    echo "$0 openstack"
    echo "   This command will read testbed description from openstack.desc"
    echo "   (or openstack/openstack.desc) and configure the nodes accordingly."
    echo ""
    echo "$0 -i 10.0.0.5 -h compute1.ec2.internal -c 10.0.0.1 controller.ec2.internal"
    echo "   This command will connect to 10.0.0.5 and configure it as a compute"
    echo "   node with controller 10.0.0.1"
    echo ""
    echo "Notes:"
    echo "This tool will use the following values from DESCFILE:"
    echo " ssh_key, controller.elastic_ip, controller_private_ip, compute*_private_ip"
    echo ""
    # restore stdout
    exec 1>&5
}

ARGS=$(getopt -o "hf:i:h:c:vn" -l "help,file:,ip:,hostname:,controller_ip:,controller_hostname:,key:,verbose,node" -n "$0" -- "$@")

if [ $? != 0 ] ; then
    msg error "error parsing command-line options"
    exit 1
fi

eval set -- "$ARGS"

while true; do
    case "$1" in
        -h|--help)
            help
            exit 0
            shift;;
        -f|--file)
            testbed_file=$2
            shift 2;;
        -i|--ip)
            node_ip=$2
            shift 2;;
        -h|--hostname)
            node_hostname=$2
            shift 2;;
        --controller_ip)
            controller_ip=$2
            shift 2;;
        --controller_hostname)
            controller_hostname=$2
            shift 2;;
        -n|--node)
            node=1
            shift;;
        -k|--key)
            ssh_key=$2
            shift 2;;
        -v|--verbose)
            verbose="-v"
            set -x
            shift;;
        --)
            shift
            break;;
        *)
            msg error "invalid command-line option: $1"
            break;;
    esac
done

parsedesc() {
    ips=()
    while IFS="=" read key value; do
        case $key in
            ssh_key)
                ssh_key=$value;;
            *elastic_ip)
                elastic_ip=$value;;
            controller.private_ip)
                controller_hostname=$testbed-${key%%.*}.ec2.internal
                controller_ip=$value
                ;;
            compute*.private_ip)
                hosts+=($testbed-${key%%.*}.ec2.internal)
                ips+=($value);;
        esac
    done < $1
}

configure_controller() {
    # wait until controller is online
    for i in {1..20}; do
        if ssh $ssh_opts $ssh_dst true; then
            break
        fi
        sleep 1
    done

    scp $ssh_opts "${files[@]}" $ssh_dst: &>/dev/null
    ssh $ssh_opts $ssh_dst "sudo bash network-setup server $controller_hostname 2>/dev/null"
    ssh $ssh_opts $ssh_dst "sudo bash puppet-openstack-configure $verbose -h $controller_hostname -e $elastic_ip $controller_hostname $controller_ip"
    scp $ssh_opts $ssh_dst:$controller_hostname.log $testbed
    scp $ssh_opts $ssh_dst:/root/openrc $testbed 2>/dev/null || true
    sed -ie "s/${controller_hostname}/${elastic_ip}/g" $testbed/openrc 2>/dev/null || true
}

configure_node() {
    scp $ssh_opts "${files[@]}" $ssh_dst: &>/dev/null
    ssh $ssh_opts $ssh_dst "sudo bash network-setup client $node_hostname $controller_ip" 2>/dev/null
    ssh $ssh_opts $ssh_dst "sudo bash puppet-openstack-configure $verbose -h $node_hostname $controller_hostname $controller_ip"
    scp $ssh_opts $ssh_dst:$node_hostname.log .
}

# global variables
hostname=$(hostname)
user=ubuntu
files=(puppet-openstack-configure site.pp node-setup network-setup)
ssh_opts="$verbose -qo UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
declare -a pids

# if testbed file wasn't specified in the command-line,
# try to find it in the $testbed directory
if (($#!=1)); then
    usage
    exit 1
fi

testbed=$1
[[ -z $testbed_file ]] && testbed_file=$1/$1.desc

if [[ -z $testbed ]]; then
    testbed=${testbed_file%.*}
    testbed=${testbed##*/}
fi

# configuring testbed from description file
if [[ -z $node ]]; then

    [[ ! -e $testbed_file ]] && msg error "$testbed_file not found"

    declare -a hosts
    parsedesc $testbed_file

    # try to find ssh key in current directory, "testbed", "keys"
    basedir=$(dirname $testbed_file)
    for dir in $basedir $testbed keys; do
        if [ -f $dir/$ssh_key.pem ]; then
            ssh_key_file=$dir/$ssh_key.pem
            break
        fi
    done
    [[ -f $ssh_key_file ]] || msg error "Could not find SSH key: $ssh_key"

    msg "Connecting to $elastic_ip"
    msg "Setting up node: $controller_hostname ($controller_ip)"

    ssh_opts+=" -i $ssh_key_file"
    files+=($ssh_key_file)
    ssh_dst="$user@$elastic_ip"

    # Configure controller by connecting via ssh and running
    # puppet-openstack-configure
    { if configure_controller; then
            msg "Successfully configured $controller_hostname"
        else
            msg error "Error configuring $controller_hostname"
        fi
    } & # run in the background
    pids+=($!)

    # wait until Puppet server is configured to start setting up compute nodes
    while sleep 5; do
        ssh $ssh_opts $ssh_dst sudo service puppetmaster status &>/dev/null && break
    done

    # Configure compute nodes by recursively calling this script from the
    # controller passing --node, the controller host/ip and the node's internal
    # ip
    for node_hostname in ${hosts[@]}; do
        node_ip=${ips[$i]}
        msg "Setting up node: $node_hostname ($node_ip)"
        ssh $ssh_opts $ssh_dst "sudo bash node-setup $verbose --node --ip $node_ip --hostname $node_hostname --controller_ip $controller_ip --controller_hostname $controller_hostname --key $ssh_key $testbed" &
        pids+=($!)
    done

    wait

    if curl -s "http://${elastic_ip}/horizon" | grep -q Dashboard; then
        msg "Setup complete. Dashboard: http://${elastic_ip}/horizon"
    fi

    scp $ssh_opts $ssh_dst:$testbed-compute*.log $testbed

# configuring node (called recursively from this script)
else
    if [[ -z $node_ip || -z $node_hostname || -z $controller_ip || \
      -z $controller_hostname || -z $ssh_key ]]; then
        usage
        exit 1
    fi

    ssh_opts+=" -i $ssh_key.pem"
    ssh_dst="$user@$node_ip"
    { if configure_node; then
        msg "Successfully configured $node_hostname"
    else
        msg error "Error configuring $node_hostname";
    fi
    scp $ssh_opts $ssh_dst:$node_hostname.log $testbed
    } &
    pids+=($!)
    wait
fi

